name: club-music-pipeline

on: push

jobs:
  deploy:
    name: Deploy pipeline
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::289866763058:role/my-github-actions-role
          aws-region: ap-southeast-2
